// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.
#ifndef GIT_REVISION_H
#define GIT_REVISION_H

static const char * BUILD_TAG = "RS-FUNSERVER";
static int BUILD_REVISION = 33;

#define BUILD_USER "Grevin"
#define BUILD_WORKSTATION "CHRONO"
#define GIT_DATE "Monday, July 20 2009"

#define BUILD_TIME "01:49AM (UTC)"
#define BUILD_DATE "Jul 20 2009"

#endif		 // SVN_REVISION_H

