// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.
#ifndef GIT_REVISION_H
#define GIT_REVISION_H

static const char * BUILD_TAG = "RS-FUNSERVER";
static int BUILD_REVISION = 63;

#define BUILD_USER "Grevin"
#define BUILD_WORKSTATION "CHRONO"
#define GIT_DATE "Wednesday, August 5, 2009"

#define BUILD_TIME "03:41PM (UTC)"
#define BUILD_DATE "Aug 5, 2009"

#endif		 // SVN_REVISION_H

